[package]
name = "air-defence"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.27"
rand = "0.9.0"
tokio = { version = "1.44.1", features = ["full"] }
