[package]
name = "air-defence"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
comfy-table = "7.1.4"
env_logger = "0.11.7"
log = "0.4.27"
rand = "0.9.0"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
